version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE_NAME}
    env_file:
      - ./.env
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'
  setup:
    image: mongo
    env_file:
      - ./.env
    depends_on:
      - mongo
    volumes:
      - ./setup:/setup
    command: bash -c "chmod +x /setup/setup.sh && /setup/setup.sh"
    #command: bash -c "apt-get update && apt-get install -y netcat && chmod +x /setup/setup.sh && /setup/setup.sh"
volumes:
  mongo:
